version: 0.2

env:
  variables:
    CACHE_CONTROL: "86400"
    S3_BUCKET: "{{S3_BUCKET}}"
    BUILD_FOLDER: "dist/timelineaws/browser"
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing source npm dependencies
      - npm install
      - npm install -g @angular/cli
  build:
    commands:
      - echo Build starting
      - ng build
artifacts:
  files:
    - "**/*"
  discard-paths: no